FROM node:18.16 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

FROM nginx:1.21

EXPOSE 80

COPY --from=build /app/dist/w2m-frontend /usr/share/nginx/html