version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "4200:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server